# Generated by Django 4.2.4 on 2024-01-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
