# Generated by Django 4.2.4 on 2024-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
